name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2.13"

      - name: Install Composer Dependencies
        run: composer update --ignore-platform-reqs

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets with Vite
        run: npm run build

      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear

      - name: Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./bullion-plus.com/
